name: VIPSlots
main: iJoshuaHD\VIPSlots
version: 0.0.4-robske_110-ALPHA7-9
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9]
load: STARTUP
author: iJoshuaHD
description: Enable VIP players to join full servers.
website: https://github.com/ijoshuahd/VIPSlots
commands:
 vips:
  description: "Set Permissions"
  permission: vips.command.vips
permissions:
  vips.command.vips:
    default: op
    description: "/vips <add/remove/list>"
